version: '3'
services:
  dbservice:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root


    volumes:
      - ./data:/var/lib/mysql

    ports:
      - 3307:3306

  appservice:
    build: .
    depends_on: 
     - dbservice
    environment:
     - spring.datasource.url=jdbc:mysql://dbservice:3306/smart_contact?createDatabaseIfNotExist=true
     - spring.datasource.username=root
     - spring.datasource.password=root
    ports:
     - 9595:9595 
